// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xooddkskoecagmchacrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2Rka3Nrb2VjYWdtY2hhY3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjM3ODIsImV4cCI6MjA2ODkzOTc4Mn0.uH4SlWEpLNu_z_7qpxYQpCBvWx3JTVgjD5KYB3hj6z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});